sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6DuXErKntuLniLTro6
    access-key-secret: sMxq4bVzIcGwQcgvfOf5wWM220qK9t
    bucket-name: sky-itcast1karus
  redis:
    host: localhost
    port: 6379
#    password: 123456
    database: 10
  wechat:
    appid: wx692c497e1767357c
    secret: d4bef68099f3813de416e5813bcc8825
